Uses of NumPy:
    
1. Arithmetic Operations
2. Statistical Operations
3. Bitwise Operations
4. Copying & Viewing Arrays
5. Stacking Arrays
6.Matrix Operations
7.Line ar Algebra
8. Broadcasting
9. Mathematical Operations
10. Searching, Sorting & Counting Linear

NUMPY IS THE LIBRARY OR PACKAGE TO HANDLE MULTIIDIMENSION ARRAEY 
1D ARREY, 2D ARRAY , 3D ARRAY 

In [2]:
import numpy as np

In [3]:
np.__version__

'2.3.5'

In [6]:
import sys
sys.version

'3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:11:29) [Clang 20.1.8 ]'

In [7]:
#  creating list 
my_list = [0,1,2,3,4,5,6]
my_list

[0, 1, 2, 3, 4, 5, 6]

In [11]:
arr = np.array(my_list)
arr


array([0, 1, 2, 3, 4, 5, 6])

In [10]:
type(my_list)

list

In [12]:
type(arr)

numpy.ndarray

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [15]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [18]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
np.arange(-20, 10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [20]:
np.arange(-16, 10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [21]:
np.arange(-20, -10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [22]:
np.arange(30,20) # it arrage < 2nd orguents

array([], dtype=int64)

In [23]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [24]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [25]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [26]:
np.zeros(10) # parameter tunning 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [31]:
np.zeros(5, dtype=int) # this is called hyperParameter tunning 

array([0, 0, 0, 0, 0])

In [32]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [34]:
np.zeros((5,6),dtype = int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [36]:
np.ones(3)

array([1., 1., 1.])

In [37]:
np.ones(2)

array([1., 1.])

In [38]:
np.ones((3), dtype =int)

array([1, 1, 1])

In [40]:
np.ones(3, dtype=int)

array([1, 1, 1])